version: '3.5'

services:
  contracts-env:
    env_file:
      - .env
    build:
      context: ./
    working_dir: /src
    command: npm run run-env
    volumes:
      - ./:/src
      - $HOME/.tenderly/config.yaml:/root/.tenderly/config.yaml
    environment:
      MNEMONIC: ${MNEMONIC}
      INFURA_KEY: ${INFURA_KEY}
      ALCHEMY_KEY: ${ALCHEMY_KEY}